#!/bin/bash

set -eo pipefail
shopt -s dotglob

mv /tmp/src/* /opt/app-root/src/

# Restore artifacts from the previous build (if they exist).
if [ -d /tmp/artifacts/.m2 ]; then
  echo "---> Restoring maven dependencies downloaded in the previous build..."
  mv /tmp/artifacts/.m2 "$HOME"/
  ls -la "$HOME"
fi

./mvnw clean package

cp -a /opt/app-root/src/target/*.jar /opt/app-root/app.jar
